### ISSUE TITLE
parfu seems to keep all directories open while scanning

### ISSUE THREAD

**Issue by rhaas80** [ncsa/parfu_archive_tool#3]
I ran a test on /mnt/c/scratch/staff/rhaas/simulations/parfu_test namely:
```bash
aprun -n 32 parfu_all_test_001 C . ../parfu32.pfu 2>&1  | tee ../parfu32.log 
```
and received an error
```
scanning directory: ./I0012_N28/output-0013
parfu_build_file_list_from_directory:
couldn't open directory >./H0011_N36/output-0008<!
There was an error in parfu_build_file_list_from_directory!!!
```

Since the number of directories parsed (grep --count scanning ../parfu32.log), 884, is close to the maximum number of open files on a compute node (echo "ulimit -n" | aprun -n1 bash), 1024, I suspect it may be leaking directory handles (ie file handles) in an opendir call.

**Comment by craigsteffen** [comment]
Um......oops?  

I was skeptical at first, because I've used this same routine for directory tress with hundreds of thousands of files.  But now that I look at the opendir() function (which I'm using, as you surmised) I see that there's a closedir() function that is typically used with it, and I'm 99% sure that I don't.  So I'm guessing I've never tested it with any directory tree that had more than 800 or so individual directories. 

How embarassing.  Um...yeah, I'll fix this, and let you know when I've deployed the (fixed) replacement.

Thanks very much, Roland!  

--Craig

**Comment by craigsteffen** [comment]
Roland, 

I've fixed the source and uploaded the patch to the head of the github repo.  So if you're building from a repo directory, just pull the new version and it should work.  

I also updated the test version in /sw on Blue Waters.  I now build it from a repo directory rather than the release tarball.  

I ran the new version on my test directory, and that worked fine, so I'm pretty sure I didn't break anything or make it any worse.  

Please let me know if this fixes the behavior you saw.

**Comment by rhaas80** [comment]
Hello Craig,

> I've fixed the source and uploaded the patch to the head of the
> github repo.  So if you're building from a repo directory, just pull
> the new version and it should work.  
> 
> I also updated the test version in /sw on Blue Waters.  I now build
> it from a repo directory rather than the release tarball.  
Thank you. I pulled and recompiled.

> Please let me know if this fixes the behavior you saw.
One thing I ran into: parfu seems to abort if the output file already
exists (which is kind of ok, though tar for example behaves
differently) but does not produce a useful error message it seems (only
that MPI_Fil_open failed but not why or for which file).

The file name for the executable is also confusing :-) Initially I
thought that parfu_all_test_001 was a unit test executable. But I
guess is means version 001 "test"?

I am now running a quick test on my data directory to see what will
happen (and also to compare to a baseline tar [<50MB/s] and my MPI
parallel tar [~110MB/s]). Given the number and size of files I seem to
be utterly dominated by MDS response time (and eg 16 or 32
parallel tar processes for my MPI tar made no difference).

I will keep you up to date as to my findings.

Yours,
Roland

-- 
My email is as private as my paper mail. I therefore support encrypting
and signing email messages. Get my PGP key from http://keys.gnupg.net.

**Comment by craigsteffen** [comment]
Thanks for all your testing, Roland.

"parfu seems to abort if the output file already
exists (which is kind of ok, though tar for example behaves
differently) but does not produce a useful error message it seems (only
that MPI_Fil_open failed but not why or for which file)."

Are you creating an archive file (mode C), and the archive file already exists?  Or are you extracting (mode X) and one (or more) of file being extracted already exist in that location? 

Having it abort if the archive file exists is the planned behavior for this very early version, although it should certainly tell you why.  You shouldn't be getting error messages from within MPI_File_Open(); I'll have to fix that.  

In the more fleshed-out test version, you indicate archive file with -f file.pfu and -F file.pfu.  The -f option aborts if archive file exists, the -F overwrites.  

I agree, the executable names are rather quixotic.  They're mostly my attempt to make sure that people understand that while each executable name will be consistent in its interface, they won't be consistent with each other until I get it all sorted out the way I want.  Once the interface is stable, then I'll just called it "parfu".  This is to make absolutely sure someone doesn't write a script assuming the CLI for one version and have it break with a different/later version. 

The performance I've seen in the past has been on the order of around 1 GB/s for archiving, mostly independent of size or number of files unless they were EXTREMELY numerous (1 Million or more).  The test I just ran was about half that; it took 600 or so seconds to archive 256 GB.  

Craig

**Comment by rhaas80** [comment]
ok with this fix it works.
I get ~240MB/s effective transfer rate (and about 300MB/s while the copying is actually going on) and a file size overhead (compared to tar) of ~7% larger file size (presumably due to some block size differences between tar and parfu).

**Comment by rhaas80** [comment]
In reply to the comment one above: yes I was creating an archive and the output archive file already existed (I had used lfs setstripe to create it since I was not sure what parfu would do for striping).  I am not getting an error message from within MPI_File_open, the error message however only states that MPI_File_open failed and gives no indication (that I could see) why it failed or which file it tried to open (eg the output file or one of the input files).

**Comment by craigsteffen** [comment]
Ok, I need to be more careful about checking for file existences.  I've created another issue for parfu to cover that.  I'll close that issue when I've fixed it.

I generally just create an archive directory with a stripe count set high, like at least 16, then the files created in that directory get that stripe count.
