### ISSUE TITLE
incorrect type used for catalog_buffer_for_ranks_length

### ISSUE THREAD

**Issue by rhaas80** [ncsa/parfu_archive_tool#5]
catalog_buffer_for_ranks_length is a long int but is passed to MPI_Bcast with a MPI_INT type. Since we are using little endian machines the low-order bytes are first so *if* accidentally the high order bytes of the variable were already zero (or of mpi's buffer) then the MPI_Bcast (which only fills the low order bytes) would give the "correct" result. Otherwise: garbage. A fix is present in commit 8fcd88a .

**Comment by craigsteffen** [comment]
right.  I understood the problem, I was just curious what variable it was.
Thanks.

**Comment by craigsteffen** [comment]
I cherry-picked Roland's fix from his branch, rolled it into a separate branch for testing.  This is tested (at the level of one create and one extract) and rolled back into the master branch.
